Vagrant.configure("2") do |config|
  config.vm.define "web" do |web|
    web.vm.box = "generic/rocky9"
    web.vm.network "private_network", ip: "192.168.56.50"
    web.vm.hostname = "web"

    web.vm.provider "virtualbox" do |vb|
        vb.cpus = "1"
        vb.memory = "1024"
    end

    web.vm.provision "shell", inline: <<-SHELL
        dnf update
        dnf install httpd -y
        systemctl enable --now httpd
        firewall-cmd --add-service http
    SHELL
  end
end